server:
  port : 8090

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/nekko-db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    queue:
      name: NEKKO_QUEUE
    exchange:
      name: nekko-exchange
    routing:
      key: nekko.key

content-manager:
  base-path: C:\Projects\nekko-like-bot\nekko-service\data\library\