package ru.vaganov.nekkolike.business.process.workflow;

public enum WorkflowStep {
    MENU,

    JOIN_STARTED,
    JOIN_WAIT_FOR_NAME,
    JOIN_COMPLETED,

    ADD_CAT_STARTED,
    ADD_CAT_WAIT_FOR_PHOTO,
    ADD_CAT_WAIT_FOR_NAME,
    ADD_CAT_WAIT_FOR_ACCEPT,
    ADD_CAT_ACCEPTED,
    ADD_CAT_COMPLETED,

    SHOW_CAT_STARTED,
    SHOW_CAT_RECEIVED,
    SHOW_CAT_REVIEW,

    MY_CATS_STARTED,
    MY_CATS_VIEW_PAGE,
    MY_CATS_VIEW_NEXT_PAGE,
    MY_CATS_VIEW_PREV_PAGE,
    MY_CATS_VIEW_CAT_INFO,
    MY_CATS_WAIT_CAT_INFO,
    MY_CATS_DELETE,
    MY_CATS_COMPLETED,
}
