

spring:
  profiles:
    active: secure

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    queue_request:
      name: NEKKO_REQUEST_QUEUE
    queue_response:
      name: NEKKO_RESPONSE_QUEUE
    exchange:
      name: nekko-exchange
    routing:
      request_key: nekko.request.key
      response_key: nekko.response.key

telegram:
  token: token
  name: name

content-manager:
  base-path: C:\Projects\nekko-like-bot\nekkolike\data\library\